[workspace]
release_always = false
changelog_update = true
git_tag_enable = true
git_release_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "LTK Manager v{{ version }}"
git_release_body = "{{ changelog }}"
git_release_type = "auto"

[[package]]
name = "ltk-manager"
publish = false
publish_no_verify = true
git_only = true
semver_check = false
changelog_update = true
cargo_package_extra_args = ["--no-verify"]

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
tag_pattern = "v[0-9].*"
sort_commits = "newest"
commit_parsers = [
    { message = "^chore: release", skip = true },
    { message = "^chore: bump version", skip = true },
    { message = "^Merge pull request", skip = true },
    { message = "^Merge branch", skip = true },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactored" },
    { message = "^docs", group = "Documentation" },
    { message = ".*", group = "Other" },
]
