// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved author profile that can be reused across workshop projects.
 */
export type AuthorProfile = {
  /**
   * Stable UUID for referencing this profile.
   */
  id: string;
  /**
   * Author display name.
   */
  name: string;
  /**
   * Default role for this author (e.g. "3D Artist").
   */
  role: string | null;
};
