// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved author profile that can be reused across workshop projects.
 */
export type AuthorProfile = { id: string; name: string; role: string | null };
