// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FantomeImportStage } from "./FantomeImportStage";

/**
 * Progress event emitted during fantome import.
 */
export type FantomeImportProgress = {
  stage: FantomeImportStage;
  currentWad: string | null;
  current: number;
  total: number;
};
