// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitImportStage } from "./GitImportStage";

/**
 * Progress event emitted during git repo import.
 */
export type GitImportProgress = { stage: GitImportStage; message: string | null };
