// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named folder for grouping mods in the library.
 */
export type LibraryFolder = { id: string; name: string; modIds: Array<string> };
