// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayStage } from "./OverlayStage";

/**
 * Progress event emitted during overlay building.
 */
export type OverlayProgress = {
  stage: OverlayStage;
  currentFile: string | null;
  current: number;
  total: number;
};
