// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry in the WAD blocklist.
 *
 * `Exact` matches a literal filename (case-insensitively). `Regex` matches
 * against every WAD filename in the game install; the pattern is always
 * applied case-insensitively.
 */
export type WadBlocklistEntry = { kind: "exact"; value: string } | { kind: "regex"; value: string };
