// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime info about a layer's content directory, fetched separately from config.
 */
export type WorkshopLayerInfo = { wadFiles: Array<string> };
